# Generated by Django 5.0 on 2023-12-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': 'Настройки', 'verbose_name_plural': 'Настройка'},
        ),
        migrations.RenameField(
            model_name='slide',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='slide',
            name='description',
            field=models.CharField(default=1, max_length=255, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='picture',
            field=models.ImageField(default=1, upload_to='user_image', verbose_name='Главная картина'),
            preserve_default=False,
        ),
    ]
