# Generated by Django 5.0 on 2023-12-13 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_slide_options_rename_name_slide_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='picture',
            new_name='image',
        ),
    ]
