# Generated by Django 5.0 on 2023-12-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_rename_picture_slide_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='description',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='title',
        ),
        migrations.AddField(
            model_name='slide',
            name='image1',
            field=models.ImageField(default=1, upload_to='Картина для we creative'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='image2',
            field=models.ImageField(default=1, upload_to='Картина для we best'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='mini_descriptions',
            field=models.CharField(default=1, max_length=255, verbose_name='Мини Описание для salimo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='mini_descriptions1',
            field=models.CharField(default=1, max_length=255, verbose_name='Мини описание для we creative'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='mini_descriptions2',
            field=models.CharField(default=1, max_length=255, verbose_name='Мини описание для we best'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='we_best',
            field=models.CharField(default=1, max_length=255, verbose_name='Название для we best'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='we_creative',
            field=models.CharField(default=1, max_length=255, verbose_name='Название для we creative'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='we_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Название salimo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(upload_to='Картина для salimo'),
        ),
    ]
