# Generated by Django 5.0 on 2023-12-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_alter_slide_image_alter_slide_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='one_page',
            field=models.ImageField(default=1, upload_to='first_icon', verbose_name='Вступление'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slide',
            name='image2',
            field=models.ImageField(upload_to=' we best', verbose_name='Картина для we best'),
        ),
    ]
