# Generated by Django 5.0 on 2023-12-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_slide_one_page_alter_slide_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='logo_black',
            field=models.ImageField(default=1, upload_to='logo_black/', verbose_name='Логотип_черный'),
            preserve_default=False,
        ),
    ]
