# Generated by Django 5.0 on 2023-12-14 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_slide_logo_black'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='logo_black',
        ),
    ]
