# Generated by Django 5.0 on 2023-12-14 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_aboutus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'Настройки', 'verbose_name_plural': 'About us'},
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='descriptions',
        ),
    ]
