# Generated by Django 5.0 on 2023-12-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_alter_aboutus_options_remove_aboutus_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='manager',
            field=models.ImageField(default=1, upload_to='Photo2', verbose_name='Фото2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='about_image',
            field=models.ImageField(upload_to='Photo1', verbose_name='Фото для About'),
        ),
    ]
