# Generated by Django 5.0 on 2023-12-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_aboutus_manager_alter_aboutus_about_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='descriptions',
            field=models.TextField(default=1, verbose_name='Описание About'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title2',
            field=models.CharField(default=1, max_length=255, verbose_name='Описание два'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='manager',
            field=models.ImageField(upload_to='photo2', verbose_name='Фото2'),
        ),
    ]
