# Generated by Django 5.0 on 2023-12-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_rename_title_aboutus_title1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='photo', verbose_name='фото_слайд')),
                ('descriptions', models.CharField(max_length=255, verbose_name='Описание')),
                ('logo', models.ImageField(upload_to='logo/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайды'},
        ),
        migrations.RemoveField(
            model_name='slide',
            name='image',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='mini_descriptions',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='mini_descriptions1',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='mini_descriptions2',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='we_best',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='we_creative',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='we_name',
        ),
    ]
