# Generated by Django 5.0 on 2023-12-14 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_settings_alter_slide_options_remove_slide_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
    ]
