# Generated by Django 5.0 on 2023-12-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0018_aboutus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='descriptions1',
            field=models.TextField(default=1, verbose_name='Описание1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='descriptions2',
            field=models.TextField(default=1, verbose_name='Описание2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='descriptions3',
            field=models.TextField(default=1, verbose_name='Описание3'),
            preserve_default=False,
        ),
    ]
