# Generated by Django 5.0 on 2023-12-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0019_remove_aboutus_descriptions_aboutus_descriptions1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meneger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_photo', models.ImageField(upload_to='manager', verbose_name='Фото менеджера')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
