# Generated by Django 5.0 on 2023-12-14 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0021_manager_delete_meneger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manager',
            new_name='Managers',
        ),
    ]
