# Generated by Django 5.0 on 2023-12-14 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0023_socialmedia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managers',
            options={'verbose_name': 'Менеджер', 'verbose_name_plural': 'Менеджера'},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'Соц.сеть', 'verbose_name_plural': 'Соц. сети'},
        ),
    ]
