# Generated by Django 5.0 on 2023-12-14 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0024_alter_managers_options_alter_socialmedia_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'Про меня', 'verbose_name_plural': 'Про нас'},
        ),
    ]
