# Generated by Django 5.0 on 2023-12-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0025_alter_aboutus_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Image', verbose_name='Фото')),
                ('testimonials', models.TextField(verbose_name='Отзывы')),
                ('name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('work', models.CharField(max_length=255, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
