# Generated by Django 5.0 on 2023-12-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0027_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cards',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
