# Generated by Django 5.0 on 2023-12-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0028_cards_name_alter_cards_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
