# Generated by Django 5.0 on 2023-12-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0029_alter_cards_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=255, verbose_name='Кол-во проектов')),
                ('home_work', models.CharField(max_length=255, verbose_name='работа дома')),
                ('office', models.CharField(max_length=255, verbose_name='Офис')),
                ('customs', models.CharField(max_length=255, verbose_name='Клиенты')),
            ],
            options={
                'verbose_name': 'Факт',
                'verbose_name_plural': 'Факты',
            },
        ),
    ]
