# Generated by Django 5.0 on 2023-12-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0030_facts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='photo', verbose_name='Фото')),
                ('name1', models.CharField(max_length=255, verbose_name='Имя')),
                ('image2', models.ImageField(upload_to='photo', verbose_name='Фото')),
                ('name2', models.CharField(max_length=255, verbose_name='Имя')),
                ('image3', models.ImageField(upload_to='photo', verbose_name='Фото')),
                ('name3', models.CharField(max_length=255, verbose_name='Имя')),
                ('image4', models.ImageField(upload_to='photo', verbose_name='Фото')),
                ('name4', models.CharField(max_length=255, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
    ]
