# Generated by Django 5.0 on 2023-12-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0031_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description1',
            field=models.CharField(default=1, max_length=255, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='description2',
            field=models.CharField(default=1, max_length=255, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='description3',
            field=models.CharField(default=1, max_length=255, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='description4',
            field=models.CharField(default=1, max_length=255, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
