# Generated by Django 5.0 on 2023-12-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0032_team_description1_team_description2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Почта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='fax',
            field=models.CharField(default=1, max_length=255, verbose_name='Факс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='phone',
            field=models.CharField(default=1, max_length=255, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='schedule',
            field=models.CharField(default=1, max_length=255, verbose_name='Расписание'),
            preserve_default=False,
        ),
    ]
