# Generated by Django 5.0 on 2023-12-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0033_settings_email_settings_fax_settings_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='image',
        ),
        migrations.AddField(
            model_name='slide',
            name='image',
            field=models.ImageField(default=1, upload_to='photo', verbose_name='фото_слайд'),
            preserve_default=False,
        ),
    ]
