# Generated by Django 5.0 on 2023-12-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0034_remove_settings_image_slide_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='name',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='one_page',
        ),
        migrations.AddField(
            model_name='settings',
            name='logo',
            field=models.ImageField(default=1, upload_to='logo/', verbose_name='Логотип'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='one_page',
            field=models.ImageField(default=1, upload_to='first_icon', verbose_name='Вступление'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='descriptions',
            field=models.CharField(default=1, max_length=255, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
