# Generated by Django 5.0 on 2023-12-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0035_remove_settings_descriptions_remove_settings_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='schedule',
            new_name='schedule1',
        ),
        migrations.AddField(
            model_name='settings',
            name='schedule2',
            field=models.CharField(default=1, max_length=255, verbose_name='Расписание2'),
            preserve_default=False,
        ),
    ]
