# Generated by Django 5.0 on 2023-12-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0036_rename_schedule_settings_schedule1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photo', verbose_name='Фото')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('data', models.CharField(max_length=255, verbose_name='Дата')),
                ('month', models.CharField(max_length=255, verbose_name='Месяц')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Стятьи',
            },
        ),
    ]
