# Generated by Django 5.0 on 2023-12-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0037_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoes', models.URLField(verbose_name='Ютюб видео')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
    ]
