# Generated by Django 5.0 on 2023-12-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0038_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AddField(
            model_name='settings',
            name='video',
            field=models.URLField(default=1, verbose_name='Ютюб видео'),
            preserve_default=False,
        ),
    ]
