# Generated by Django 5.0 on 2023-12-15 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0042_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='description3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='description4',
        ),
        migrations.RemoveField(
            model_name='team',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='team',
            name='name2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='name3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='name4',
        ),
    ]
