# Generated by Django 5.0 on 2023-12-16 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0043_remove_team_description2_remove_team_description3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='description1',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='image1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name1',
            new_name='name',
        ),
    ]
