# Generated by Django 5.0 on 2023-12-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0044_rename_description1_team_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='schedule1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Расписание'),
        ),
    ]
