# Generated by Django 5.0 on 2023-12-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0045_alter_settings_schedule1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='fax',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Факс'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='schedule2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Расписание2'),
        ),
    ]
