# Generated by Django 5.0 on 2023-12-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0046_alter_settings_email_alter_settings_fax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Почта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settings',
            name='fax',
            field=models.CharField(default=1, max_length=255, verbose_name='Факс'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settings',
            name='phone',
            field=models.CharField(default=1, max_length=255, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settings',
            name='schedule1',
            field=models.CharField(default=1, max_length=255, verbose_name='Расписание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settings',
            name='schedule2',
            field=models.CharField(default=1, max_length=255, verbose_name='Расписание2'),
            preserve_default=False,
        ),
    ]
