# Generated by Django 5.0 on 2023-12-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0047_alter_settings_email_alter_settings_fax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='logo',
            field=models.ImageField(upload_to='logo', verbose_name='Логотип'),
        ),
    ]
