# Generated by Django 5.0 on 2023-12-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0048_alter_settings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='facebook',
            field=models.URLField(default=1, verbose_name='facebook'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='instagram',
            field=models.URLField(default=1, verbose_name='Instagram'),
            preserve_default=False,
        ),
    ]
