# Generated by Django 5.0 on 2023-12-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0052_team_google'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='facebook',
        ),
        migrations.AddField(
            model_name='team',
            name='telegram',
            field=models.URLField(default=1, verbose_name='telegram'),
            preserve_default=False,
        ),
    ]
