# Generated by Django 5.0 on 2023-12-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0054_remove_socialmedia_linkedin_remove_socialmedia_skype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='google',
            field=models.URLField(default=1, verbose_name='Google'),
            preserve_default=False,
        ),
    ]
