# Generated by Django 5.0 on 2023-12-16 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0057_managers_facebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managers',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='managers',
            name='telegram',
        ),
    ]
